# Generated by Django 5.2.4 on 2026-01-12 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proforma_invoice', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='proformainvoice',
            name='courier_mode',
            field=models.CharField(choices=[('surface', 'Surface'), ('air', 'Air')], default='surface', max_length=10),
        ),
    ]
