# Generated by Django 5.2.4 on 2026-01-12 06:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_inventoryitem_expected_quantity'),
        ('proforma_invoice', '0002_proformainvoice_courier_mode'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourierCharge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode', models.CharField(choices=[('surface', 'Surface'), ('air', 'Air')], default='surface', max_length=10)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courier_sheets', to='inventory.inventoryitem')),
            ],
            options={
                'unique_together': {('product', 'mode')},
            },
        ),
        migrations.CreateModel(
            name='CourierChargeTier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_quantity', models.PositiveIntegerField()),
                ('max_quantity', models.PositiveIntegerField(blank=True, null=True)),
                ('charge', models.DecimalField(decimal_places=2, max_digits=10)),
                ('courier_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tiers', to='proforma_invoice.couriercharge')),
            ],
            options={
                'ordering': ['min_quantity'],
            },
        ),
    ]
