# Generated by Django 5.2.4 on 2026-02-21 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proforma_invoice', '0004_proformapricechangerequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='proformainvoice',
            name='is_price_altered',
            field=models.BooleanField(default=False),
        ),
    ]
