# Generated by Django 5.2.4 on 2026-04-21 07:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_dashboard', '0009_paymentdiscussionthread_paymentexpecteddatehistory_and_more'),
        ('proforma_invoice', '0005_proformainvoice_is_price_altered'),
    ]

    operations = [
        migrations.AddField(
            model_name='proformainvoice',
            name='shipping_customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shipping_invoices', to='customer_dashboard.customer'),
        ),
        migrations.AlterField(
            model_name='proformainvoice',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer_dashboard.customer'),
        ),
    ]
