# Generated by Django 5.2.4 on 2026-04-21 07:17

import django.core.serializers.json
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proforma_invoice', '0006_proformainvoice_shipping_customer_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProformaStockShortageRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shortage_details', models.JSONField(encoder=django.core.serializers.json.DjangoJSONEncoder)),
                ('status', models.CharField(choices=[('pending', 'Pending Approval'), ('approved', 'Stock Confirmed'), ('rejected', 'Unavailable')], default='pending', max_length=20)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('invoice', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='stock_request', to='proforma_invoice.proformainvoice')),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_reviewed', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
