# Generated by Django 5.2.4 on 2026-04-21 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proforma_invoice', '0007_proformastockshortagerequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='proformainvoice',
            name='dispatch_status',
            field=models.CharField(choices=[('processing', 'Still Processing'), ('pending', 'Pending'), ('dispatched', 'Dispatched')], default='processing', max_length=20),
        ),
    ]
