# Generated by Django 5.2.4 on 2026-04-21 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proforma_invoice', '0008_proformainvoice_dispatch_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='proformapricechangerequest',
            name='review_remark',
            field=models.TextField(blank=True, null=True),
        ),
    ]
