# Generated by Django 5.2.4 on 2026-04-23 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proforma_invoice', '0009_proformapricechangerequest_review_remark'),
    ]

    operations = [
        migrations.AddField(
            model_name='proformainvoice',
            name='dispatch_requested_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='proformainvoice',
            name='dispatched_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
