# Generated by Django 5.2.4 on 2026-04-27 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proforma_invoice', '0010_proformainvoice_dispatch_requested_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proformapricechangerequest',
            name='review_remark',
        ),
    ]
