# Generated by Django 5.2.4 on 2026-05-03 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proforma_invoice', '0012_proformaremark'),
    ]

    operations = [
        migrations.AddField(
            model_name='productprice',
            name='msrp',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, help_text='The ceiling price. Requests above this are auto-approved.', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='proformainvoice',
            name='is_converted_to_pi',
            field=models.BooleanField(default=False, help_text='Converted-pi'),
        ),
        migrations.AddField(
            model_name='proformainvoiceitem',
            name='current_courier_charge',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Current - courier', max_digits=10),
        ),
        migrations.AddField(
            model_name='proformainvoiceitem',
            name='current_msrp',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Current - MSRP', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='proformainvoiceitem',
            name='current_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Price at time of creation', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='proformainvoiceitem',
            name='customer_name_snapshot',
            field=models.CharField(blank=True, help_text='customer', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='proformainvoiceitem',
            name='made_by',
            field=models.CharField(blank=True, help_text='made-by', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='proformainvoiceitem',
            name='requested_courier_charge',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Requested - courier', max_digits=10),
        ),
        migrations.AddField(
            model_name='proformainvoiceitem',
            name='requested_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Price requested by user', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='proformainvoiceitem',
            name='stock_requested',
            field=models.IntegerField(default=0, help_text='Stock-requested (Integer)'),
        ),
    ]
