# Generated by Django 5.2.4 on 2026-05-04 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proforma_invoice', '0013_productprice_msrp_proformainvoice_is_converted_to_pi_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='proformapricechangerequest',
            name='needs_accountant_approval',
            field=models.BooleanField(default=False, help_text='True if any requested price is below MSRP'),
        ),
    ]
