# Generated by Django 5.2.4 on 2026-05-04 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proforma_invoice', '0014_proformapricechangerequest_needs_accountant_approval'),
    ]

    operations = [
        migrations.AddField(
            model_name='productpricetier',
            name='msrp',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, help_text='The ceiling price. Requests above this are auto-approved.', max_digits=10, null=True),
        ),
    ]
