# Generated by Django 5.2.4 on 2026-05-04 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proforma_invoice', '0016_salespersonpricethreshold'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proformapricechangerequest',
            name='needs_accountant_approval',
        ),
        migrations.DeleteModel(
            name='SalespersonPriceThreshold',
        ),
    ]
