# Generated by Django 5.2.4 on 2026-05-04 11:37

import django.core.serializers.json
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_dashboard', '0010_customer_gst_number_customer_shipping_address_and_more'),
        ('inventory', '0007_inventoryitem_expected_quantity'),
        ('proforma_invoice', '0017_remove_proformapricechangerequest_needs_accountant_approval_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='proformapricechangerequest',
            name='accountant_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='proformapricechangerequest',
            name='customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='customer_dashboard.customer'),
        ),
        migrations.AddField(
            model_name='proformapricechangerequest',
            name='is_permitted',
            field=models.BooleanField(default=False, help_text='Ticked if this price/customer combo was already approved in the past'),
        ),
        migrations.AddField(
            model_name='proformapricechangerequest',
            name='is_under_msrp',
            field=models.BooleanField(default=False, help_text='True if ANY item in this request is priced below its MSRP'),
        ),
        migrations.AddField(
            model_name='proformapricechangerequest',
            name='superuser_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='proformapricechangerequest',
            name='requested_product_prices',
            field=models.JSONField(blank=True, encoder=django.core.serializers.json.DjangoJSONEncoder, help_text='Stores requested price, recommended price, and MSRP snapshot per item', null=True),
        ),
        migrations.CreateModel(
            name='ApprovedPriceMemory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_approved_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('base_price_at_approval', models.DecimalField(decimal_places=2, max_digits=10)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer_dashboard.customer')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.inventoryitem')),
            ],
            options={
                'unique_together': {('customer', 'product')},
            },
        ),
    ]
