# Generated by Django 5.2.4 on 2026-05-07 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proforma_invoice', '0018_proformapricechangerequest_accountant_approved_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='proformapricechangerequest',
            name='courier_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10),
        ),
    ]
