# Generated by Django 5.2.4 on 2026-05-08 09:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_inventoryitem_expected_quantity'),
        ('proforma_invoice', '0019_proformapricechangerequest_courier_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proformapricechangerequest',
            name='requested_product_prices',
        ),
        migrations.AddField(
            model_name='proformapricechangerequest',
            name='is_product_request',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='proformapricechangerequest',
            name='is_this_product_price',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='proformapricechangerequest',
            name='msrp_snapshot',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='proformapricechangerequest',
            name='product',
            field=models.ForeignKey(blank=True, help_text='Only required if is_product_request is True', null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.inventoryitem'),
        ),
        migrations.AddField(
            model_name='proformapricechangerequest',
            name='recommended_courier_charge',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='proformapricechangerequest',
            name='recommended_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='proformapricechangerequest',
            name='requested_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
